### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by pombredanne** [wahern/phf#5]
Hi:
What's the license for this library?
Thanks!

**Comment by wahern** [comment]
It's at the top of the source files, phf.h and phf.cc.

I've committed a LICENSE file for Github's benefit.

**Comment by pombredanne** [comment]
@wahern Thanks... Gee I was completely and desperately blind. Sorry for the noise!

**Comment by wahern** [comment]
No sweat. It happens to all of us. Just pay it forward ;)
